### ISSUE TITLE
Serviço de comparação de resultados de reprodução

### ISSUE THREAD

**Issue by fernandocandrade** [ONSBR/aplicacao_teste_sager#18]
O serviço deverá obter as 2 memórias de cálculo e comparar os resultados, conforme layout estipulado para a funcionalidade. o sistema deve baixar o resultado do processamento em uma planilha excel para visualização.

**Comment by fernandocandrade** [comment]
Implementado o business de negócio para comparação e o parser de geração da planilha

**Comment by Canellas** [comment]
Caros Srs.,

Alguém pode, por favor, retirar meu e-mail da lista de destinatários?

Grato,

Rodrigo Canellas
(enviado do celular)

Em 20 de fev de 2018 09:49, "Fernando Andrade" <notifications@github.com>
escreveu:

**Comment by PMoneda** [comment]
Canellas, tudo bem?!

Para parar de receber emails você tem que ir em todos os repositórios do time e ignorar o repositório a partir da tag watch no canto superior direito da tela ao lado do star

**Comment by Canellas** [comment]
Vou proceder conforme orientação.


Se está "tudo bem"?  Não, obviamente não está tudo bem. Obrigado por
perguntar.



    Rodrigo Canellas
    επιμονή


2018-03-07 14:35 GMT-03:00 Phlippe Moneda <notifications@github.com>:
