### ISSUE TITLE
Refatorar todas as consultas implementadas nos casos de uso

### ISSUE THREAD

**Issue by fernandocandrade** [ONSBR/aplicacao_teste_sager#27]
Refatorar todas as consultas implementadas nos casos de uso com o novo formato de filtros de mapas da plataforma, pois foi alterado

**Comment by fernandocandrade** [comment]
As mudanças foram realizadas, mas a camada de domínio não está pronta, com o estado equivalente a versão anterior, pois os dados não estão sendo salvos ainda, isto impacta outras atividades.

**Comment by jeanesaldanha** [comment]
Issue migrada para Done em 26/04/2018.
