### ISSUE TITLE
Reteste da reprodução (bug da plataforma resolvidos do branch)

### ISSUE THREAD

**Issue by fernandocandrade** [ONSBR/aplicacao_teste_sager#29]
Está com dependência da atividade #27, para ser realizada, caso não finalize, não será realizada

**Comment by fernandocandrade** [comment]
Está com dependência da atividade #28, para ser realizada, caso não finalize, não será realizada

**Comment by jeanesaldanha** [comment]
Issue migrada para Done em 23/05/2018.
