### ISSUE TITLE
Regras de negócio de consistências de eventos para o reprocessamento, chamado a partir do caso de uso UC-00601

### ISSUE THREAD

**Issue by fernandocandrade** [ONSBR/aplicacao_teste_sager#30]

**Comment by fernandocandrade** [comment]
As demais funções foram implementadas, mas essa função é que fará uso propriamente da plataforma para 
reprocessar, como não temos o reprocessar ainda na plataforma, faremos a aplicação das várias regras previstas, 
e já selecionadas com apoio da analista

**Comment by jeanesaldanha** [comment]
Issue migrada para Done em 23/05/2018.
